### ISSUE TITLE
cc-metric-store `invalid timestamp: line-protocol value out of range`

### ISSUE THREAD

**Issue by BlackLotus** [ClusterCockpit/cc-metric-store#31]
When trying to configure cc cc-metric-collector sends the following line
```
cpu_system,cluster=testcluster,hostname=hpc-dev-cpu01,type=node,unit=Percent value=0.399993142477566 1731078075204515557
```
This leads to this problem in cc-metric-store
```
 /api/write error (decoding line protocol for cluster 'testcluster'): timestamp : 0x3 with error : "invalid timestamp: line-protocol value out of range"
```
When trying to take a closer look at the situation I tried to add some debugging code to decodeLine in https://github.com/ClusterCockpit/cc-metric-store/blob/main/internal/api/lineprotocol.go
For instance https://github.com/ClusterCockpit/cc-metric-store/blob/main/internal/api/lineprotocol.go#L267
and I realize that there are many unknown tags and most of the time when this error occurs a unknown tag is present as well.
Is this the intended behavior?

**Comment by adityauj** [comment]
Hi @BlackLotus,
The epoch timestamp you specify is in nanoseconds. CCMS only supports epoch timestamp in seconds as of now.
Could you please specify the epoch timestamp in seconds and then try again ?

**Comment by BlackLotus** [comment]
Switched to developer branch for it to work. It would be really nice to either merge it or write all of this into the documentation.
Should I keep the issue open until it is merged/documented or should I close the issue?
Anyway thank you so much for the help

**Comment by adityauj** [comment]
As of now there should be no difference between main branch or devel branch because main branch was merged from devel branch a few days ago. Both should function exactly the same way. =)

The current problem is with the timestamp handling, so regardless of the tags, it will fail.
However, I am kind of skeptical with the assertion that specifying unknown tags also throws this error.
I will check and create an issue myself if I find it that it fails with unknown tags. It should not in general.

Also, I would rather open an enhancement to support nanoseconds or seconds automatically from influxDB line protocol. It is documented [here](https://www.clustercockpit.org/docs/reference/cc-metric-store/ccms-rest-api/) with an example but still it specifies nanoseconds. We will get it done.
