### ISSUE TITLE
cc-metric-store does not write any data

### ISSUE THREAD

**Issue by BlackLotus** [ClusterCockpit/cc-metric-store#32]
Here is the (probably) relevant snippet from the config
```
    "checkpoints": {
        "interval": "12h",
        "directory": "/opt/monitoring/cc-metric-store/var/checkpoints",
        "restore": "48h"
    },
    "archive": {
        "interval": "50h",
        "directory": "/opt/monitoring/cc-metric-store/var/archive"
    },
```
When stopping the server after a successful write I get this
```
2024/11/08 18:10:13 /api/write succeeded for cluster 'testcluster'
^C2024/11/08 18:10:17 Writing to '/opt/monitoring/cc-metric-store/var/checkpoints'...
2024/11/08 18:10:17 Done! (0 files written)
2024/11/08 18:10:17 Graceful shutdown completed!
```
Is it normal that no data is written?

**Comment by adityauj** [comment]
Hi @BlackLotus 

This can happen you write the data for the metrics which are not present in the config.json. So when you write the data using write endpoint, the API will check if the given metric in lineprotocol matches the metric list from config.json.

If the metric is not present, then Buffers will not be created for those metrics, and hence during immediate shutdown after write, no files will be created (since there is no data).

Can you try to debug the root object from memorystore a bit and see if actually the data is inserted ??

In general you can understand about the CCMS architecture here : https://www.clustercockpit.org/docs/architecture/metric_store/

**Comment by BlackLotus** [comment]
Seems to work as expected. Thanks for the quick answer
